
#![allow(non_camel_case_types, non_upper_case_globals, non_snake_case)]
/* automatically generated by rust-bindgen */

#[doc = ""]
#[doc = " This class defines global limits for input and output of all modules."]
#[doc = ""]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct FALimits {
    pub _address: u8,
}