
#![allow(non_camel_case_types, non_upper_case_globals, non_snake_case)]
/* automatically generated by rust-bindgen */

#[doc = ""]
#[doc = " This class defines global limits for input and output of all modules."]
#[doc = ""]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct FALimits {
    pub _address: u8,
}
pub const FALimits_MaxArrSize: FALimits__bindgen_ty_1 = 1000000000;
pub const FALimits_MaxChainSize: FALimits__bindgen_ty_1 = 1000000000;
pub const FALimits_MaxStateVal: FALimits__bindgen_ty_1 = 1000000000;
pub const FALimits_MaxIwVal: FALimits__bindgen_ty_1 = 1000000000;
pub const FALimits_MaxIw: FALimits__bindgen_ty_1 = 1000000000;
pub const FALimits_MaxLdbDumpCount: FALimits__bindgen_ty_1 = 105;
pub const FALimits_MaxWordLen: FALimits__bindgen_ty_1 = 300;
pub const FALimits_MaxWordSize: FALimits__bindgen_ty_1 = 300;